### ISSUE TITLE
Katastrofa

### ISSUE THREAD

**Issue by juraj222** [G43riko/foods#8]
ked kliknem vyber restauracii vyhladam si lunch break a chcem si ho pridat medzi svoje prida mi inu, skusim znova aprida dalsiu inu

**Comment by G43riko** [comment]
Chyba bola spôsobená neuvážením iterovaním pola z reštauráciámi.  Pre vygenerovanie elementov bolo použité pole na ktoré sa aplikoval filter, no do DragAndDrop komponentu sa posielalo pole na ktoré tento filter nebol aplikovaný
